[wheels]

[wheels.zoom]
on_show = [
  { SetWheelColor = [ 255, 0, 0 ] },
  { ShowBanner = [ 2, "Zoom" ] }
]
on_clockwise_start = [
  { Key = [ "Control", "Press" ] },
]
on_clockwise = [
  { Key = [ { Unicode = "+" }, "Click" ] },
]
on_clockwise_stop = [
  { Key = [ "Control", "Press" ] },
]
on_counterclockwise_start = [
  { Key = [ "Control", "Press" ] },
]
on_counterclockwise = [
  { Key = [ { Unicode = "-" }, "Click" ] },
]
on_counterclockwise_stop = [
  { Key = [ "Control", "Press" ] },
]
on_click = [
  { ChangeWheel = "Next" }
]
on_double_click = [
  { ChangeWheel = "Previous" }
]

[buttons.hola]
on_press = [
  { ShowBanner = [ 3, "Hola Mundo!" ] },
  { SetButtonText = [ "Button0", "hola$0" ] },
  { SetButtonText = [ "Button1", "hola$1" ] },
  { SetButtonText = [ "Button2", "hola$2" ] },
  { SetButtonText = [ "Button3", "hola$3" ] },
  { SetButtonText = [ "Button4", "hola$4" ] },
  { SetButtonText = [ "Button5", "hola$5" ] },
  { SetButtonText = [ "Button6", "hola$6" ] },
  { SetButtonText = [ "Button7", "hola$7" ] },
  { Text = "Hello!" }
]


[buttonsets.navigation]
button1="hola"

[profiles.niano.buttonsets]
first="navigation"

[profiles.niano.wheels]

zoom="zoom"

