[wheels]

[wheels.zoom]
on_enter = [
  { SetWheelColor = [ 255, 0, 0 ] }
]
on_clockwise_start = [
  { ShowBanner = [ 2, "-- Zoom In --" ] },
  { Key = [ "Control", "Press" ] },
]
on_clockwise = [
  { Key = [ { Unicode = "+" }, "Click" ] },
]
on_clockwise_stop = [
  { Key = [ "Control", "Release" ] },
]
on_counterclockwise_start = [
  { ShowBanner = [ 2, "-- Zoom Out --" ] },
  { Key = [ "Control", "Press" ] },
]
on_counterclockwise = [
  { Key = [ { Unicode = "_" }, "Click" ] },
]
on_counterclockwise_stop = [
  { Key = [ "Control", "Release" ] },
]
on_click = [
  { ChangeWheel = "Next" }
]
on_double_click = [
  { ChangeWheel = "Previous" }
]
on_long_press = [
  { ShowBanner = [ 2, "-- Zoom 100% --" ] },
  { Key = ["Control", "Press"] },
  { Key = [ { Unicode = "0" }, "Click" ] },
  { Key = ["Control", "Release"] },
]

[wheels.volume]
on_enter = [
  { SetWheelColor = [ 255, 255, 0 ] }
]
on_clockwise = [
  { Text = "Volume Up" }
]
on_counterclockwise = [
  { Text = "Volume Down" }
]
on_click = [
  { ChangeWheel = "Next" }
]
on_long_press = [
  { Text = "Volume 50%" }
]
on_double_click = [
  { ChangeWheel = "Previous" }
]

[wheels.mouse_horizontal]
on_clockwise = [
  { MoveMouse = [ 10, 0, "Rel" ] }
]
on_counterclockwise = [
  { MoveMouse = [ -10, 0, "Rel" ] }
]
on_press = [
  { ChangeWheel = "Next" }
]

[wheels.mouse_vertical]
on_clockwise = [
  { MoveMouse = [ 0, 10, "Rel" ] }
]
on_counterclockwise = [
  { MoveMouse = [ 0, -10, "Rel" ] }
]
on_press = [
  { ChangeWheel = "Next" }
]

[buttons.next]
on_press = [
  { ChangeButtonSet = "Next" }
]
on_long_press = [
  { ChangeProfile = [ "Next", "First", "First" ] }
]


[buttons.hola]
on_double_click = [
  { Text = "Hi!" }
]

[buttons.adios]
on_press = [
  { SetButtonText = [ "Button0", "adios$0" ] },
  { SetButtonText = [ "Button1", "adios$1" ] },
  { SetButtonText = [ "Button2", "adios$2" ] },
  { SetButtonText = [ "Button3", "adios$3" ] },
  { SetButtonText = [ "Button4", "adios$4" ] },
  { SetButtonText = [ "Button5", "adios$5" ] },
  { SetButtonText = [ "Button6", "adios$6" ] },
  { SetButtonText = [ "Button7", "adios$7" ] },
  { Text = "Bye!" }
]

[buttons.say_hi]
on_press = [ { Text = "Hi!" } ]

[buttons.move_mouse_left]
on_press = [
  { MoveMouse = [ -10, 0, "Rel" ] },
  { ChangeWheel = { Name = "mouse_horizontal" } }
]

[buttons.move_mouse_right]
on_press = [
  { MoveMouse = [ 10, 0, "Rel" ] },
  { ChangeWheel = { Name = "mouse_horizontal" } }
]

[buttons.move_mouse_up]
on_press = [
  { MoveMouse = [ 0, -10, "Rel" ] },
  { ChangeWheel = { Name = "mouse_vertical" } }
]

[buttons.move_mouse_down]
on_press = [
  { MoveMouse = [ 0, 10, "Rel" ] },
  { ChangeWheel = { Name = "mouse_vertical" } }
]
[buttons.left_click]
on_press = [
  { Button = [ "Left", "Click" ] }
]
[buttons.middle_click]
on_press = [
  { Button = [ "Middle", "Click" ] }
]
[buttons.right_click]
on_press = [
  { Button = [ "Right", "Click" ] }
]



[buttonsets.bts1]
on_enter = [
  { SetButtonText = [ "Button0", "Say$Hi!" ] },
  { SetButtonText = [ "Button1", "hola$1" ] },
  { SetButtonText = [ "Button2", "hola$2" ] },
  { SetButtonText = [ "Button3", "hola$3" ] },
  { SetButtonText = [ "Button4", "hola$4" ] },
  { SetButtonText = [ "Button5", "hola$5" ] },
  { SetButtonText = [ "Button6", "hola$6" ] },
  { SetButtonText = [ "Button7", "hola$7" ] },
]
button_extra="next"

[buttonsets.bts2]
on_enter = [
  { SetButtonText = [ "Button0", "bts2$0" ] },
  { SetButtonText = [ "Button1", "bts2$1" ] },
  { SetButtonText = [ "Button2", "bts2$2" ] },
  { SetButtonText = [ "Button3", "bts2$3" ] },
  { SetButtonText = [ "Button4", "bts2$4" ] },
  { SetButtonText = [ "Button5", "bts2$5" ] },
  { SetButtonText = [ "Button6", "bts2$6" ] },
  { SetButtonText = [ "Button7", "bts2$7" ] },
]
button_extra="next"

[buttonsets.mouse]
on_enter = [
  { SetButtonText = [ "Button0", "H" ] },
  { SetButtonText = [ "Button1", "J" ] },
  { SetButtonText = [ "Button2", "K" ] },
  { SetButtonText = [ "Button3", "L" ] },
  { SetButtonText = [ "Button4", "Left$Button" ] },
  { SetButtonText = [ "Button5", "Middle$Button" ] },
  { SetButtonText = [ "Button6", "Right$Button" ] },
  { SetButtonText = [ "Button7", "" ] },
]
button0="move_mouse_left"
button1="move_mouse_down"
button2="move_mouse_up"
button3="move_mouse_right"
button4="left_click"
button5="middle_click"
button6="right_click"
button_extra="next"

[profiles.niano.buttonsets]
first="bts1"
second="bts2"

[profiles.niano.wheels]
zoom="zoom"
volume="volume"

[profiles.mouse.buttonsets]
mouse="mouse"

[profiles.mouse.wheels]
mouse_horizontal="mouse_horizontal"
mouse_vertical="mouse_vertical"
