[macros]
clean_buttons = [
  { SetButtonText = [ "Button0", "" ] },
  { SetButtonText = [ "Button1", "" ] },
  { SetButtonText = [ "Button2", "" ] },
  { SetButtonText = [ "Button3", "" ] },
  { SetButtonText = [ "Button4", "" ] },
  { SetButtonText = [ "Button5", "" ] },
  { SetButtonText = [ "Button6", "" ] },
  { SetButtonText = [ "Button7", "" ] },
]
tmux_cmd = [
  { Key = [ "Control", "Press" ] },
  { Key = [ { Unicode = "b" }, "Click" ] },
  { Key = [ "Control", "Release" ] },
]


[wheels]

[wheels.zoom]
on_enter = [
  { SetWheelColor = [ 255, 0, 0 ] },
  { SetWheelSpeed = "Slowest" }
]
on_clockwise_start = [
  { ShowBanner = [ 2, "-- Zoom In --" ] },
  { Key = [ "Control", "Press" ] },
]
on_clockwise = [
  { Key = [ { Unicode = "+" }, "Click" ] },
]
on_clockwise_stop = [
  { Key = [ "Control", "Release" ] },
]
on_counterclockwise_start = [
  { ShowBanner = [ 2, "-- Zoom Out --" ] },
  { Key = [ "Control", "Press" ] },
]
on_counterclockwise = [
  { Key = [ { Unicode = "_" }, "Click" ] },
]
on_counterclockwise_stop = [
  { Key = [ "Control", "Release" ] },
]
on_click = [
  { ChangeWheel = "Next" }
]
on_double_click_press = [
  { ChangeWheel = "Previous" }
]
on_long_press = [
  { ShowBanner = [ 2, "-- Zoom 100% --" ] },
  { Key = ["Control", "Press"] },
  { Key = [ { Unicode = "0" }, "Click" ] },
  { Key = ["Control", "Release"] },
]

[wheels.volume]
on_enter = [
  { SetWheelColor = [ 255, 255, 0 ] },
  { SetWheelSpeed = "Slower" }
]
on_clockwise = [
  { Run = [ "pulsemixer", "--max-volume", "100", "--change-volume", "+5" ] }
]
on_counterclockwise = [
  { Run = [ "pulsemixer", "--max-volume", "100", "--change-volume", "-5" ] }
]
on_click = [
  { ChangeWheel = "Next" }
]
on_long_press = [
  { Run = [ "pulsemixer", "--max-volume", "100", "--toggle-mute" ] }
]
on_double_click_press = [
  { ChangeWheel = "Previous" }
]

[wheels.mouse_horizontal]
on_enter = [
  { SetWheelColor = [ 255, 192, 203 ] },
  { SetWheelSpeed = "Fastest" }
]
on_clockwise = [
  { MoveMouse = [ 10, 0, "Rel" ] }
]
on_counterclockwise = [
  { MoveMouse = [ -10, 0, "Rel" ] }
]
on_press = [
  { ChangeWheel = "Next" }
]

[wheels.mouse_vertical]
on_enter = [
  { SetWheelColor = [ 255, 192, 203 ] },
  { SetWheelSpeed = "Fastest" }
]
on_clockwise = [
  { MoveMouse = [ 0, 10, "Rel" ] }
]
on_counterclockwise = [
  { MoveMouse = [ 0, -10, "Rel" ] }
]
on_press = [
  { ChangeWheel = "Next" }
]

[wheels.mouse_diagonal_1]
on_enter = [
  { SetWheelColor = [ 255, 192, 203 ] },
  { SetWheelSpeed = "Fastest" }
]
on_clockwise = [
  { MoveMouse = [ 10, 10, "Rel" ] }
]
on_counterclockwise = [
  { MoveMouse = [ -10, -10, "Rel" ] }
]
on_press = [
  { ChangeWheel = "Next" }
]

[wheels.mouse_diagonal_2]
on_enter = [
  { SetWheelColor = [ 255, 192, 203 ] },
  { SetWheelSpeed = "Fastest" }
]
on_clockwise = [
  { MoveMouse = [ 10, -10, "Rel" ] }
]
on_counterclockwise = [
  { MoveMouse = [ -10, 10, "Rel" ] }
]
on_press = [
  { ChangeWheel = "Next" }
]

[buttons.next]
on_click_release = [
  { ChangeButtonSet = "Next" }
]
on_long_press = [
  { ChangeProfile = [ "Next", "First", "First" ] }
]

[buttons.center_mouse]
on_enter = [
  { SetButtonText = [ "ThisButton", "><" ] }
]
on_press = [
  { MoveMouse = [ 1440, 900, "Abs" ] }
]

[buttons.adios]
on_press = [
  { Text = "Bye!" }
]

[buttons.say_hi]
on_press = [ { Text = "Hi!" } ]

[buttons.mouse_horizontal]
on_enter = [
  { SetButtonText = [ "ThisButton", "-" ] }
]
on_press = [
  { ChangeWheel = { Name = "mouse_horizontal" } }
]

[buttons.mouse_diagonal_2]
on_enter = [
  { SetButtonText = [ "ThisButton", "/" ] },
]

on_press = [
  { ChangeWheel = { Name = "mouse_diagonal_2" } }
]

[buttons.mouse_diagonal_1]
on_enter = [
  { SetButtonText = [ "ThisButton", "\\" ] },
]
on_press = [
  { MoveMouse = [ 0, -10, "Rel" ] },
  { ChangeWheel = { Name = "mouse_diagonal_1" } }
]

[buttons.mouse_vertical]
on_enter = [
  { SetButtonText = [ "ThisButton", "|" ] }
]
on_press = [
  { ChangeWheel = { Name = "mouse_vertical" } }
]

[buttons.left_click]
on_enter = [
  { SetButtonText = [ "ThisButton", "Left" ] }
]
on_press = [
  { Button = [ "Left", "Press" ] }
]
on_release = [
  { Button = [ "Left", "Release" ] }
]

[buttons.middle_click]
on_enter = [
  { SetButtonText = [ "ThisButton", "Middle" ] },
]
on_press = [
  { Button = [ "Middle", "Press" ] }
]
on_release = [
  { Button = [ "Middle", "Release" ] }
]

[buttons.right_click]
on_enter = [
  { SetButtonText = [ "ThisButton", "Right" ] }
]
on_press = [
  { Button = [ "Right", "Press" ] }
]
on_release = [
  { Button = [ "Right", "Release" ] }
]


[buttons.tmux_split_vertical]
on_enter = [
  { SetButtonText = [ "ThisButton", "Split$||" ] }
]
on_press = [
  { Macro = "tmux_cmd" },
  { Key = [ { Unicode = "%" }, "Click" ] },
]

[buttons.tmux_split_horizontal]
on_enter = [
  { SetButtonText = [ "ThisButton", "Split$--" ] }
]
on_press = [
  { Macro = "tmux_cmd" },
  { Key = [ { Unicode = "\"" }, "Click" ] },
]

[buttons.tmux_windows]
on_enter = [
  { SetButtonText = [ "ThisButton", "Windows" ] }
]
on_press = [
  { Macro = "tmux_cmd" },
  { Key = [ { Unicode = "w" }, "Click" ] },
]



[buttonsets.tmux]
on_enter = [
  { Macro = "clean_buttons" },
]
button1 = "tmux_split_vertical"
button2 = "tmux_split_horizontal"
button4 = "tmux_windows"
button_extra="next"

[buttons.neovim_hardmode]
on_enter = [
  { SetButtonText = [ "ThisButton", "HardMode" ] },
]
on_press = [
  { Key = [ "Escape", "Click" ] },
  { Text = ":HardTimeToggle" },
  { Key = [ "Return", "Click" ] },
]

[buttonsets.neovim]
on_enter = [
  { Macro = "clean_buttons" },
]
button7="neovim_hardmode"
button_extra="next"

[buttonsets.mouse]
button0="mouse_horizontal"
button1="mouse_vertical"
button2="mouse_diagonal_1"
button3="mouse_diagonal_2"
button4="left_click"
button5="middle_click"
button6="right_click"
button7="center_mouse"
button_extra="next"

[buttons.test_button]
on_enter = [
  { SetButtonText = [ "ThisButton", "* Test *" ] }
]
on_press = [ { Debug = "on_press" } ]
on_release = [ { Debug = "on_release" } ]
on_click_press = [ { Debug = "on_click_press" } ]
on_click = [ { Debug = "on_click" } ]
on_click_release = [ { Debug = "on_click_release" } ]
on_double_click_press = [ { Debug = "on_double_click_press" } ]
on_double_click = [ { Debug = "on_double_click" } ]
on_double_click_release = [ { Debug = "on_double_click_release" } ]
on_triple_click_press = [ { Debug = "on_triple_click_press" } ]
on_triple_click = [ { Debug = "on_triple_click" } ]
on_triple_click_release = [ { Debug = "on_triple_click_release" } ]
on_long_press = [ { Debug = "on_long_press" } ]

[buttonsets.test]
on_enter = [
  { Macro = "clean_buttons" },
]
button0="test_button"
button1="test_button"
button2="test_button"
button3="test_button"
button4="test_button"
button5="test_button"
button6="test_button"
button7="test_button"
button_extra="next"

[profiles.shell]
on_enter = [ 
  { ShowBanner = [ 2, "-- SHELL --" ] },
]

[profiles.shell.buttonsets]
test="test"
tmux="tmux"
neovim="neovim"

[profiles.shell.wheels]
zoom="zoom"
volume="volume"

[profiles.mouse]
on_enter = [ 
  { ShowBanner = [ 2, "-- MOUSE --" ] },
]

[profiles.mouse.buttonsets]
mouse="mouse"

[profiles.mouse.wheels]
mouse_horizontal="mouse_horizontal"
mouse_vertical="mouse_vertical"
mouse_diagonal_1="mouse_diagonal_1"
mouse_diagonal_2="mouse_diagonal_2"
